### ISSUE TITLE
3.0.1插件

### ISSUE THREAD

**Issue by chinasmu** [fjqisba/E-debug-plus#1]
3.0.1插件下载不了。
用vs2017编译不成功。。。。

**Comment by fjqisba** [comment]
额，你倒是把错误发出来看看啊，我的是VS2015编译环境

**Comment by chinasmu** [comment]
最新版本点击 静态编译 会出异常OD退出
另外没有界面显示了啊，感觉很不方便，希望还是会有主界面
希望可以写个简短的教程说明，谢谢

**Comment by fjqisba** [comment]
我重新上传了,https://github.com/fjqisba/E-debug-plus/releases/download/1.0.2/plugin.7z
使用没什么好说明的,扫描模式的代码暂时没写.
如果有崩溃的样本可以发给我，就这样..
