### ISSUE TITLE
Esig Not Founded

### ISSUE THREAD

**Issue by chinasmu** [fjqisba/E-debug-plus#2]
为什么我分析的软件具体调用都显示Esig Not Founded，就只有KrnlLinCmd几个系统函数可以先生出来

支持库信息里各个库都有调用命令数，就是具体点开没命令名称

**Comment by fjqisba** [comment]
没有找到Esig后缀文件,原因可能为:
未制作相应支持库的Esig
相应支持库的Esig版本号不同
插件存在BUG

**Comment by fjqisba** [comment]
新版本决定将这些不同版本的特征库合并,版本号什么的不存在了
