### ISSUE TITLE
请求交流

### ISSUE THREAD

**Issue by paituo** [fjqisba/E-debug-plus#3]
你好。最近在分析一个易语言的程序，找到你这个插件。插件非常不错，而且还在更新维护中。我在分析中发现些问题想和你交流下。例如对krnlCmd中最后一个函数的作用等。
		pEAnalysisEngine->AnalysisMode = StaticMode;
		vector<string> krnlCmd =
		{ "错误回调", "DLL命令", "三方支持库命令", "核心支持库命令",
			"读取组件属性", "设置组件属性", "分配内存", "重新分配内存",
			"释放内存", "结束", "窗口消息循环", "载入启动窗口", "初始化" };

       同时有想法将插件移植到X64DBG上，如有必要可以直接移植到IDA上。

我Q：330435863

**Comment by fjqisba** [comment]
BUG反馈与交流QQ群:633783602
