### ISSUE TITLE
能不能添加一点新功能啊？

### ISSUE THREAD

**Issue by Rixo1043** [fjqisba/E-debug-plus#4]
我使用的时候其实不是很清楚取十六字节和到字节集两个键的作用。
问题：在使用时其实发现需要每到一个模块再使用一次分析，分析窗口还不能关闭.
希望的解决方案：
1.能不能分析之后自动在OD里面写个注释或标签，
2.根据模块名字先应用相关的库特征，如果分析不准确，可以支持手动添加库特征继续分析
3.解释一下取十六字节和到字节集两个键的作用。

**Comment by fjqisba** [comment]
1和2这个功能不是已经实现了吗?
3这个功能只要用过易语言应该都了解

**Comment by Rixo1043** [comment]
╮（﹀_﹀）╭我是在分析一个易语言病毒时发现你的插件的，之前并没有接触过易语言。然后这个易语言病毒用的易语言版本是一个做了一些混淆免杀的版本，所幸并不是强加密，在病毒解密执行时，使用这个插件还是能有很多函数分析出来的。
所以，1，2功能确实没有遇到，3功能的话我确实不太懂，百度也没有相关解释，如果你能帮忙解释一下的话就太感激了。
为了证明一下我并没有瞎说，特地找到了之前跟的类似IAT的部分给你截了一张图。
![image](https://user-images.githubusercontent.com/22998321/71407843-290e7b00-2677-11ea-9375-8cb3d4509f5f.png)

**Comment by fjqisba** [comment]
难怪，易语言有三种编译出来的程序，编译和独立编译(二者区别不大)，还有静态编译，你这个是属于前者，我已经在说明里写了:
编译或者独立编译的程序,由于软件数目少,研究难度低,暂时也懒得去写了.
功能3就是单纯的拷贝数据而已，例如E8 01 02 03这个机器码
取十六进制结果为E8010203
取字节集结果为{232,1,2,3}
